(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const c of t)if(c.type==="childList")for(const a of c.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const c={};return t.integrity&&(c.integrity=t.integrity),t.referrerPolicy&&(c.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?c.credentials="include":t.crossOrigin==="anonymous"?c.credentials="omit":c.credentials="same-origin",c}function n(t){if(t.ep)return;t.ep=!0;const c=r(t);fetch(t.href,c)}})();const I="LibraryDB",i="books",d="booklist",E=2;let h=null,u=[],f=[],s=1;const m=10;let l=new Set;function S(){return new Promise((e,o)=>{const r=indexedDB.open(I,E);r.onupgradeneeded=n=>{const t=n.target.result;t.objectStoreNames.contains(i)||t.createObjectStore(i,{keyPath:"bookId"}),t.objectStoreNames.contains(d)||t.createObjectStore(d,{keyPath:"bookId"})},r.onsuccess=n=>e(n.target.result),r.onerror=n=>o(n.target.error)})}async function w(){try{h=await S();const r=h.transaction([d],"readonly").objectStore(d).getAll();r.onsuccess=()=>{u=r.result||[],u.reverse(),y()},r.onerror=n=>console.error("Error loading books:",n)}catch(e){console.error("Failed to open DB:",e)}}function y(){const e=document.getElementById("searchInput").value.toLowerCase();e?f=u.filter(o=>{const r=(o.title||"").toLowerCase(),n=(o.author||"").toLowerCase();return r.includes(e)||n.includes(e)}):f=u,s=1,b()}function b(){const e=document.getElementById("bookGrid"),o=document.getElementById("emptyState"),r=document.getElementById("pageInfo"),n=document.getElementById("prevBtn"),t=document.getElementById("nextBtn");if(e.innerHTML="",f.length===0){o.style.display="block",e.style.display="none",r.textContent="0 / 0",n.disabled=!0,t.disabled=!0;return}o.style.display="none",e.style.display="grid";const c=Math.ceil(f.length/m);s>c&&(s=c),s<1&&(s=1);const a=(s-1)*m,p=a+m;f.slice(a,p).forEach(k=>{const v=L(k);e.appendChild(v)}),r.textContent=`${s} / ${c}`,n.disabled=s===1,t.disabled=s===c}function L(e){const o=document.createElement("div");o.className="book-card";const r=e.cover||"icons/icon128.png",n=l.has(e.bookId)?"checked":"";o.innerHTML=`
        <div class="book-checkbox-wrapper ${n?"checked":""}">
            <input type="checkbox" class="book-checkbox" ${n}>
        </div>
        <div class="cover-wrapper">
            <img src="${r}" alt="${e.title}" onerror="this.src='icons/icon128.png'">
        </div>
        <div class="book-info">
            <div class="book-title" title="${e.title}">${e.title||"Tanpa Judul"}</div>
            <div class="book-author" title="${e.author}">${e.author||"Tanpa Pengarang"}</div>
            <div class="actions">
                <button class="download-btn" title="Unduh File">
                    Unduh Buku
                </button>
                <button class="delete-btn" title="Hapus Buku">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="3 6 5 6 21 6"></polyline>
                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                        <line x1="10" y1="11" x2="10" y2="17"></line>
                        <line x1="14" y1="11" x2="14" y2="17"></line>
                    </svg>
                </button>
            </div>
        </div>
    `;const t=o.querySelector(".download-btn");t.onclick=()=>x(e);const c=o.querySelector(".delete-btn");c.onclick=()=>O(e);const a=o.querySelector(".book-checkbox"),p=o.querySelector(".book-checkbox-wrapper");return a.onchange=g=>{g.target.checked?(l.add(e.bookId),p.classList.add("checked")):(l.delete(e.bookId),p.classList.remove("checked")),B()},o}async function x(e){try{const n=h.transaction([i],"readonly").objectStore(i).get(e.bookId);n.onsuccess=()=>{const t=n.result;if(t&&t.file){const c=t.file,a=t.ext||"pdf",g=`${(e.title||"book").replace(/[/\\?%*:|"<>]/g,"-")}.${a}`,k=URL.createObjectURL(c);chrome.downloads.download({url:k,filename:g,saveAs:!0},v=>{setTimeout(()=>URL.revokeObjectURL(k),1e3),chrome.runtime.lastError&&(console.error(chrome.runtime.lastError),alert("Gagal memulai download: "+chrome.runtime.lastError.message))})}else alert("File tidak ditemukan di database. Silakan unduh ulang dari website.")},n.onerror=()=>alert("Gagal mengambil file dari database.")}catch(o){console.error("Download error:",o)}}async function O(e){if(confirm(`Apakah Anda yakin ingin menghapus buku "${e.title}"?`))try{const o=h.transaction([i,d],"readwrite"),r=o.objectStore(i),n=o.objectStore(d);r.delete(e.bookId),n.delete(e.bookId),o.oncomplete=()=>{u=u.filter(t=>t.bookId!==e.bookId),y()},o.onerror=t=>{console.error("Delete failed:",t),alert("Gagal menghapus buku: "+t.target.error)}}catch(o){console.error("Delete error:",o)}}function B(){const e=document.getElementById("bulkActionBar"),o=document.getElementById("selectedCount");o.textContent=l.size,l.size>0?e.classList.add("visible"):e.classList.remove("visible")}function P(){l.clear(),b(),B()}function $(){const e=(s-1)*m,o=e+m,r=f.slice(e,o);let n=!0;for(const t of r)if(!l.has(t.bookId)){n=!1;break}n?r.forEach(t=>l.delete(t.bookId)):r.forEach(t=>l.add(t.bookId)),b(),B()}async function j(){if(l.size!==0&&confirm(`Hapus ${l.size} buku yang dipilih?`))try{const e=h.transaction([i,d],"readwrite"),o=e.objectStore(i),r=e.objectStore(d);let n=0;for(const t of l)o.delete(t),r.delete(t),n++;e.oncomplete=()=>{u=u.filter(t=>!l.has(t.bookId)),l.clear(),y(),B()},e.onerror=t=>{console.error("Bulk delete failed:",t),alert("Gagal menghapus beberapa buku.")}}catch(e){console.error("Bulk delete error:",e)}}document.addEventListener("DOMContentLoaded",()=>{w(),document.getElementById("searchInput").addEventListener("input",y),document.getElementById("prevBtn").addEventListener("click",()=>{s>1&&(s--,b())}),document.getElementById("nextBtn").addEventListener("click",()=>{const o=Math.ceil(f.length/m);s<o&&(s++,b())}),document.getElementById("selectAllBtn").addEventListener("click",$),document.getElementById("deleteSelectedBtn").addEventListener("click",j),document.getElementById("cancelSelectionBtn").addEventListener("click",P)});
